# Generated by Django 5.2.16 on 2026-07-17 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('telegram_channel_id', models.BigIntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('voice', 'Voice'), ('document', 'Document')], max_length=20)),
                ('telegram_file_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachings', to='categories.category')),
            ],
            options={
                'ordering': ['-published_at', '-telegram_message_id'],
                'indexes': [models.Index(fields=['-published_at'], name='teachings_t_publish_6eea03_idx'), models.Index(fields=['media_type'], name='teachings_t_media_t_7dff86_idx')],
                'constraints': [models.UniqueConstraint(fields=('telegram_channel_id', 'telegram_message_id'), name='uniq_teaching_channel_message')],
            },
        ),
    ]
