# Generated by Django 5.2.16 on 2026-07-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='local_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
