# Generated by Django 5.2.16 on 2026-07-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0005_add_download_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teaching',
            new_name='teachings_t_downloa_a37307_idx',
            old_name='teachings_t_downloa_idx',
        ),
    ]
